#include <stdio.h>
#include <stdlib.h>

// Converts a .bin file to a C header with XOR-encoded byte array
// The output header is included at compile time with -DEMBED

int main(int argc, char *argv[]) {
    if (argc < 3) {
        printf("bin2header — Convert .bin to C header for embedded mode\n\n");
        printf("Usage: %s <input.bin> <output.h> [xor_key 0-255]\n", argv[0]);
        return 1;
    }

    const char *in_path = argv[1];
    const char *out_path = argv[2];
    unsigned char key = (argc >= 4) ? (unsigned char)atoi(argv[3]) : 0;

    FILE *fin = fopen(in_path, "rb");
    if (!fin) {
        printf("[-] Cannot open: %s\n", in_path);
        return 1;
    }

    fseek(fin, 0, SEEK_END);
    long len = ftell(fin);
    fseek(fin, 0, SEEK_SET);

    unsigned char *buf = (unsigned char *)malloc(len);
    fread(buf, 1, len, fin);
    fclose(fin);

    // XOR encode
    if (key != 0) {
        for (long i = 0; i < len; i++) {
            buf[i] ^= key;
        }
    }

    FILE *fout = fopen(out_path, "w");
    if (!fout) {
        printf("[-] Cannot write: %s\n", out_path);
        free(buf);
        return 1;
    }

    fprintf(fout, "// Auto-generated by bin2header\n");
    fprintf(fout, "// Source: %s | Size: %ld bytes", in_path, len);
    if (key != 0) fprintf(fout, " | XOR key: 0x%02X", key);
    fprintf(fout, "\n\n");
    fprintf(fout, "unsigned char embedded_shellcode[] = {\n    ");

    for (long i = 0; i < len; i++) {
        fprintf(fout, "0x%02X", buf[i]);
        if (i < len - 1) fprintf(fout, ",");
        if ((i + 1) % 16 == 0 && i < len - 1) fprintf(fout, "\n    ");
    }

    fprintf(fout, "\n};\n");
    fprintf(fout, "unsigned int embedded_shellcode_len = %ld;\n", len);

    fclose(fout);
    free(buf);

    printf("[+] Header generated: %s\n", out_path);
    printf("[+] %ld bytes", len);
    if (key != 0) printf(" (XOR key: 0x%02X — use loader.exe -e -x %d)", key, key);
    printf("\n");

    return 0;
}
